export const RANGE_CHANGE_STARTED = 'RANGE_CHANGE_STARTED';
export const RANGE_CHANGED = 'RANGE_CHANGED';

export const RANGE_RESET_STARTED = 'RANGE_RESET_STARTED';
export const RANGE_RESET = 'RANGE_RESET';
