export const PAGE_TITLE_CHANGE_STARTED = 'PAGE_TITLE_CHANGE_STARTED';
export const PAGE_TITLE_CHANGED = 'PAGE_TITLE_CHANGED';

export const AGE_CHANGE_STARTED = 'AGE_CHANGE_STARTED';
export const AGE_CHANGED = 'AGE_CHANGED';

export const RANGE_CHANGE_STARTED = 'RANGE_CHANGE_STARTED';
export const RANGE_CHANGED = 'RANGE_CHANGED';

export const RANGE_RESET_STARTED = 'RANGE_RESET_STARTED';
export const RANGE_RESET = 'RANGE_RESET';
